trigger:
  branches:
    include:
      - refs/tags/release-bindings-v*

pr: none

pool:
  vmImage: 'macOS-13'

variables:
  - group: nuget.org

steps:

- bash: |
    echo "##vso[task.setvariable variable=bindingsVersion]$(cat Xamarin.RevenueCatUI.iOS/Xamarin.RevenueCatUI.iOS.csproj | grep '<Version>' | awk -F '[<>]' '{print $3}')"

- bash: |
    echo "##vso[build.updatebuildnumber]xamarin-revenuecatui-ios-bindings-$(Build.SourceBranchName)-$(Build.BuildId)"

- bash: |
    if [[ "$(Build.SourceBranchName)" != *"$(bindingsVersion)" ]]; then
      echo "mismatch between tag $(Build.SourceBranchName) and nuget version $(bindingsVersion)"
      exit 1
    fi

- bash: |
    cd Xamarin.RevenueCatUI.iOS
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release

- bash: |
    dotnet nuget push Xamarin.RevenueCatUI.iOS/nugetoutput/Xamarin.RevenueCatUI.iOS.*.nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Xamarin.RevenueCat.iOS'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceBranchName)'
    title: 'Xamarin.RevenueCatUI.iOS Bindings $(bindingsVersion)'
    assets: 'Xamarin.RevenueCatUI.iOS/nugetoutput/Xamarin.RevenueCatUI.iOS.*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
